hub/urls.py
from django.urls import path

from . import views

app_name = 'hub'

urlpatterns = [
    path('', views.HubMainView.as_view(), name='index'),
]

myblacksmith/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.models import User
from rest_framework import routers

from accounts.views import UserViewSet
from tasks.views import TaskViewSet
from projects.views import ProjectViewSet
from labels.views import LabelViewSet


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet, basename = 'users')
router.register(r'tasks', TaskViewSet, basename = 'tasks')
router.register(r'projects', ProjectViewSet, basename = 'projects')
router.register(r'labels', LabelViewSet, basename = 'labels')

urlpatterns = [
    path('', include('hub.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('chess/', include('chess.urls')),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
    path('labels/', include('labels.urls')),
    path('admin/', admin.site.urls),

    path('api-auth/', include('rest_framework.urls')),
    path('api/', include(router.urls)),
]

projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.ProjectsView.as_view(), name="projects"),
    path('create/', views.CreateProject.as_view(), name="create_project"),
    path('<int:pk>/', views.ProjectDetail.as_view(), name="project"),
    path('<int:pk>/update', views.UpdateProject.as_view(), name="update_project"),
    path('<int:pk>/delete', views.DeleteProject.as_view(), name="delete_project"),
]

projects/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

class Project(models.Model):
    name = models.CharField(max_length = 256)
    user = models.ForeignKey(get_user_model(), on_delete = models.CASCADE)
    description = models.CharField(max_length = 2048)
    creation_date = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

from projects.models import Project
from labels.models import Label

class Task(models.Model):
    project = models.ForeignKey(Project, on_delete = models.CASCADE, blank = True, null = True)
    user = models.ForeignKey(get_user_model(), on_delete = models.CASCADE, editable=False)
    name = models.CharField(max_length = 256)
    text = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now, editable=False)
    labels = models.ManyToManyField(Label)

    def __str__(self):
        return self.name if not self.project else "{}@{}".format(self.name, self.project)

class Comment(models.Model):
    task = models.ForeignKey(Task, related_name = 'comments', on_delete = models.CASCADE, editable=False)
    user = models.ForeignKey(get_user_model(), on_delete = models.CASCADE, editable=False)
    text = models.TextField()
    creation_date = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.text[:30]

projects/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy

from rest_framework import viewsets
from rest_framework import permissions
from .serializers import ProjectSerializer

from .models import Project

class ProjectsView(LoginRequiredMixin, generic.ListView):
    template_name = 'projects/projects.html'
    context_object_name = 'project_list'

    def get_queryset(self):
        return Project.objects.all().filter(user = self.request.user.id)

class CreateProject(LoginRequiredMixin, generic.CreateView):
    template_name = 'projects/create.html'
    model = Project
    fields = ['name', 'description']

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(reverse('projects:projects'))

class ProjectDetail(LoginRequiredMixin, generic.DetailView):
    template_name = 'projects/project.html'
    model = Project

    def get_queryset(self):
        return super().get_queryset().filter(user = self.request.user.id)

class UpdateProject(LoginRequiredMixin, generic.UpdateView):
    template_name = "projects/update.html"
    model = Project
    fields = ['name', 'description']

    def get_queryset(self):
        return Project.objects.all().filter(user = self.request.user.id)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(reverse('projects:project', kwargs={'pk': self.kwargs['pk']}))

class DeleteProject(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy('projects:projects')

    def get_queryset(self):
        return Project.objects.all().filter(user = self.request.user.id)



#######################
#         API         #
#######################

class ProjectViewSet(viewsets.ModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_superuser:
            return Project.objects.all()
        return Project.objects.all().filter(id = self.request.user.id)

projects/templates/projects/create.html
{% extends 'parts/base.html' %}
{% block page %}
<div class="box">
    <h2>Create a new project</h2>
        <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create project</button>
    </form>
</div>
{% endblock %}

projects/templates/projects/project.html
{% extends 'parts/base.html' %}
{% load static %}

{% block extra_head %}
<link rel="stylesheet" href="{% static 'projects/css/projects.css' %}" />
{% endblock %}

{% block page %}
<div class="box container">
    <div class="item">
        <a href="/projects/{{ project.id }}"><img class="button grow-anim" src="{% static 'img/bs.png' %}"/></a>
    </div>
    <div class="item">
        <h2 class="project-title">{{ project.name }}</h2>
        <p class="project-description">{{ project.description }}</p>
    </div>
    <div class="item">
        <a href="/projects/{{ project.id }}/delete"><svg class="button grow-anim" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg></a>
        <a href="/projects/{{ project.id }}/update"><img class="button grow-anim" src="{% static 'img/setting.png' %}"/></a>
    </div>
</div>

<div class="grey-box-container">
<a href="/tasks/create"><div class="grey-box grow-anim">
    <h2>Create New Task</h2>
    <img src="{% static 'img/plus.png' %}" class="grey-box-logo"/>
</div></a>
{% for task in project.task_set.all %}
<a href="/tasks/{{ task.id }}"><div class="grey-box grow-anim">
    <h2>{{ task.name }}</h2>
    <p>{{ task.text }}</p>
</div></a>
{% endfor %}
</div>
{% endblock %}

projects/templates/projects/project_confirm_delete.html
{% extends 'parts/base.html' %}
{% block page %}
<form method="post">{% csrf_token %} 
    <p>Are you sure you want to delete "{{ object }}"?</p> 
    <input type="submit" value="Confirm"> 
</form> 
{% endblock %}

projects/templates/projects/projects.html
{% extends 'parts/base.html' %}
{% load static %}
{% block page %}
<div id="project-list" class="grey-box-container">
    <a href="/projects/create"><div class="grey-box grow-anim">
        <h2>Create New Project</h2>
        <img src="{% static 'img/plus.png' %}" class="grey-box-logo"/>
    </div></a>

    {% for project in project_list %}
    <a href="/projects/{{ project.id }}"><div class="grey-box grow-anim">
            <h2>{{ project.name }}</h2>
            <img src="{% static 'img/bs.png' %}" class="grey-box-logo"/>
        </div></a>
    {% endfor %}
</div>

{% endblock %}

projects/templates/projects/update.html
{% extends 'parts/base.html' %}
{% load static %}
{% block page %}
<div class="box">
    <h2>Project</h2>
    <form method="POST">
        {% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Update">
    </form>
</div>
{% endblock %}